### ISSUE TITLE
BPTI example or any Protein

### ISSUE THREAD

**Issue by amrhamedp** [noegroup/paper_boltzmann_generators#3]
Hello Dr Noe,
Can you please provide an example in the notebooks demonstrating the transformation of protein into whitened Cartesian and internal coordinates?
I know that BPTI trajectory is provided by Dr Shaw. I am just looking for the model itself.

**Comment by psolsson** [comment]
Hi. You can download a self-contained example [here](http://ftp.mi.fu-berlin.de/pub/solsson/BG_BPTI.tar.gz)

**Comment by amrhamedp** [comment]
> Hi. You can download a self-contained example [here](http://ftp.mi.fu-berlin.de/pub/solsson/BG_BPTI.tar.gz)

There are missing classes:
from deep_boltzmann.models.openmm import OpenMMEnergy
from deep_boltzmann.models.proteins import mdtraj2Z
Those are not here i believe

**Comment by franknoe** [comment]
This is the original submission (not revision). Please check out the latest code there:

     https://zenodo.org/record/3242635#.XhTkd-t7lTY

The link is also given in the paper under "code availability", close to the acknowledgements. Unfortunately it is very hidden, but it is journal style to put it there.

**Comment by amrhamedp** [comment]
Thank you very much...I really appreciate this. The work is really great.

**Comment by xiaoyinyang** [comment]
Hi, can I know the version of tensorflow you used? Thanks!

**Comment by ParthGoyal1508** [comment]
Hi @franknoe, 

I'm facing an issue while executing the file `particle_dimer_test.py`

`Traceback (most recent call last):
  File "particle_dimer_test.py", line 6, in <module>
    from deep_boltzmann.models import ParticleDimer
  File "<frozen zipimport>", line 259, in load_module
  File "/home/parth/env/lib/python3.8/site-packages/Deep_Boltzmann_Package-0.1-py3.8.egg/deep_boltzmann/__init__.py", line 3, in <module>
    from deep_boltzmann.models.double_well import DoubleWell
ModuleNotFoundError: No module named 'deep_boltzmann.models'
`

Could you please help with this? Thanks

**Comment by amrhamedp** [comment]
Use the code in science article and not this one.

**Comment by ParthGoyal1508** [comment]
Hi @amrhamedp,

I have used the code which was mentioned in the paper under "code availability".
 [ https://zenodo.org/record/3242635#.XhTkd-t7lTY](https://zenodo.org/record/3242635#.XhTkd-t7lTY)
 
 For setup, I ran two commands 

`python3 setup.py build`
`python3 setup.py install`
 
 but after executing the `particle_dimer_test.py` file it throws the above error, Is there any installation step am I missing?
